channels:
  - pytorch
  - huggingface
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - numpy
  - scipy
  - matplotlib
  - tqdm
  - pillow
  - scikit-learn
  - pandas
  - pyarrow
  - pyroaring
  - cudatoolkit=11.3
  - pytorch>=1.11
  - torchvision>=0.12
  - torchmetrics
  - hdbscan
  - umap-learn
  - pycocotools
  - plotnine
  - bokeh
  - transformers
  - datasets
  - pydantic
 ## serving deps:
  - nginx
  - uvicorn
  - fastapi
  - jupyter
  - pip:
    - ipykernel
    - py-spy
    - pytorch-lightning>=1.5
    - ray[default]>=1.9
    - ray[serve]
    - ray[tune]
    - tensorboard
    - einops
    - psutil
    - pydantic-to-typescript
    - scann
