dependencies:
  - python=3.8
  - pip
  - numpy
  - scipy
  - scikit-learn
  - pandas
  - pyarrow
  - pillow
  - pytorch>=1.8
  - torchvision>=0.9 # without this I sometimes see a really old version (0.2) installed
  - tensorboard
  - flask
  - cudatoolkit>=11.1
  # - pynndescent
  - cvxpy
  - pip:
    - bokeh
    - ray[default]==1.6
    - tqdm
    - pytorch-lightning
    - torchmetrics
    - ipyvue
    - pyroaring
    - plotnine
    - annoy
    - notebook
    - ipykernel
    - ipywidgets
    - ftfy 
    - regex
    - git+https://github.com/openai/CLIP.git
channels:
  - pytorch
  - nvidia
  - conda-forge
  - anaconda